name: Linting and formatting on PR and Commit

on:
  pull_request:
    branches:
      - "**" # Runs on pull requests for all branches
  push:
    branches:
      - "**" # Runs on any push to any branch

jobs:
  Continuous-Integration:
    name: Performs linting and formatting on the application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # - name: Run linting check
      #   run: npm run lint:check

      - name: Check formatting
        run: npm run format:check

      - name: preetier formatting
        run:  npx prettier --write
